# Generated by Django 2.2.3 on 2019-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190717_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
