# Generated by Django 2.2.3 on 2019-07-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
    ]
