# Generated by Django 2.2.3 on 2019-07-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_remove_report_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_author',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
