# Generated by Django 2.2.3 on 2019-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_comments_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_author',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
