# Generated by Django 2.2.3 on 2019-07-19 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20190719_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
