# Generated by Django 2.2.3 on 2019-07-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20190719_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
