# Generated by Django 2.2.3 on 2019-07-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_problem',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_published_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_subtype',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
    ]
