# Generated by Django 2.2.3 on 2019-07-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20190720_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
