# Generated by Django 2.2.3 on 2019-07-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
