# Generated by Django 2.2.3 on 2019-07-20 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0014_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=200)),
                ('report_subtype', models.CharField(max_length=200)),
                ('report_problem', models.CharField(max_length=200)),
                ('report_published_date', models.DateTimeField()),
                ('report_photo', models.ImageField(upload_to='problems')),
                ('report_description', models.CharField(max_length=300)),
                ('report_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
